### PR TITLE
Add remainder operator (`%`) to grammar

### LINKED ISSUE #10: Remainder '%' not recognized as operator
Hi there, and thanks for this excellent project!

Trying it out now for the purpose of supporting Rego in the Zed editor via an extension, and using the tree sitter grammar from here 😃 I'm sure we'll find more things along the way, but the first thing I noticed was that it seems like the remainder operator `%` isn't recognized as one in this grammar.

Not sure if it's just as simple as adding it to the grammar.json file or if there's more to it? I haven't worked with tree-sitter grammar before.

### LINKED ISSUE #14: Move corpus directory under test/ ?
I couldn't figure out why the tests weren't working until I read this:

https://tree-sitter.github.io/tree-sitter/creating-parsers#command-test

> For each rule that you add to the grammar, you should first create a test that describes how the syntax trees should look when parsing that rule. These tests are written using specially-formatted text files in the test/corpus/ directory within your parser’s root folder.

Should we move the `corpus` dir under a new `test` directory?

### PR DESCRIPTION
**Pull request by anderseknert**
Not sure if there is something more I need to do. I basically just edited the
grammar.js file, followed by `yarn generate`. I also finally got `yarn build`
after downgrading node, but while it successfully built, it didn't seem to
change anything (which I guess is as it should be?).

Also, move `corpus` dir under `test` as per the official docs.

Fixes #10
Fixes #14

### CODE REVIEW

**Comment by FallenAngel97** [comment]
Hi @anderseknert  :smile: 
Thanks for this PR. 
Seems fine  from my side. Regarding the NodeJS - you could have used NVM, there is this file in the root of the repo, but I guess, I'll add it to the README, so it will make more sense next time. 
Regarding the remainder operator -  all tests seem to pass on my local and in Github. 
May I ask you to add unit tests in the "corpus" directory? 
So that future contributions will not screw up your work. 
You can look into the "rules.txt" file and add there your own set of checks with the remainder

**Comment by anderseknert** [comment]
@FallenAngel97 I've added tests now! But I had to move them under `test` in order to run them, as I mentioned in #14 ... so this would resolve that too if merged.

Thanks for having the patience with us despite not working actively on the project any longer 😃

**Comment by anderseknert** [comment]
Not sure what the build is failing for, or what the cause would be:
```
Force-pushing changes...
/usr/bin/git push --force ***github.com/FallenAngel97/tree-sitter-rego.git github-pages-deploy-action/t88zk4sni:gh-pages
remote: Permission to FallenAngel97/tree-sitter-rego.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/FallenAngel97/tree-sitter-rego.git/': The requested URL returned error: 403
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/t88zk4sni
Reset branch 'github-pages-deploy-action/t88zk4sni'
/usr/bin/chmod -R +rw github-pages-deploy-action-temp-deployment-folder
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Notice: Deployment failed! ❌
```

**Comment by anderseknert** [comment]
@FallenAngel97 any idea what's causing that build failure?

**Comment by FallenAngel97** [comment]
Hey @anderseknert 
Checked locally, can confirm - everything works as expected
image

For me, previous variant of directory structures was working, but I don't see any issues with renaming it. 
I'll merge it. 
TBH, don't know, why the build step might fail
Thanks for your work

**Comment by anderseknert** [comment]
Thank you! 😃

**Pull request merged**
